name: aplicacion_boceto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  flutter_stripe: ^11.2.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/usuario.png
    - assets/banos_termales.jpg
    - assets/taller_ceramica.jpg
    - assets/termales.jpg
    - assets/ceramica.jpg
    - assets/tarata_fondo.jpg
    - assets/tarata_logo.png
    - assets/relax.jpg
    - assets/yunga.jpg
    - assets/senderismo.jpg
    - assets/rutas.jpg
    - assets/canopy.jpg
    - assets/zipline_bike.jpg
    - assets/puente_tibetano.jpg
    - assets/columpio_extremo.jpg
    - assets/juegos_extremos.gif
    - assets/sitio.png
    - assets/camino.png
    - assets/qala.png
    - assets/plaza.png
    - assets/mercado.png
    - assets/iglesia.jpg
    - assets/municipalidad.png
    - assets/usuario.jpeg
    - assets/qr.jpeg