// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANw-PAqX0xt8JwbYLyBsibhY0FSPoXkSs',
    appId: '1:571529167047:web:46ab2163d40a535e923ee2',
    messagingSenderId: '571529167047',
    projectId: 'lab2firebase-5d8b3',
    authDomain: 'lab2firebase-5d8b3.firebaseapp.com',
    storageBucket: 'lab2firebase-5d8b3.firebasestorage.app',
    measurementId: 'G-33ZH7SJ6Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFbeVzoMcUSqq0BrahQDF5lvZ6h5vzJKg',
    appId: '1:571529167047:android:ab8477ed1c306403923ee2',
    messagingSenderId: '571529167047',
    projectId: 'lab2firebase-5d8b3',
    storageBucket: 'lab2firebase-5d8b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcnAP3_3LqG5w-o59OepTi5_ujf4wwvIw',
    appId: '1:571529167047:ios:227d3625cefef8fe923ee2',
    messagingSenderId: '571529167047',
    projectId: 'lab2firebase-5d8b3',
    storageBucket: 'lab2firebase-5d8b3.firebasestorage.app',
    iosClientId: '571529167047-i6rqt1oams4hch3h2liqccngr9v3g5nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicacionBoceto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANw-PAqX0xt8JwbYLyBsibhY0FSPoXkSs',
    appId: '1:571529167047:web:46ab2163d40a535e923ee2',
    messagingSenderId: '571529167047',
    projectId: 'lab2firebase-5d8b3',
    authDomain: 'lab2firebase-5d8b3.firebaseapp.com',
    storageBucket: 'lab2firebase-5d8b3.firebasestorage.app',
    measurementId: 'G-33ZH7SJ6Q0',
  );
}
